name: Merge to Main Workflow

on:
  push:
    branches:
      - main

jobs:
  merge_to_main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: npm ci
      - run: npm run test:coverage
      - name: Push coverage report to main branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add report-main.json
          git diff-index --quiet HEAD || git commit -m 'Update coverage stats'
      - name: Push changes
        run: git push
