name: Merge to Main Workflow

on:
  push:
    branches:
      - main

jobs:
  merge_to_main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: npm ci
      - run: npm run test:coverage
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          path: coverage/coverage-summary.json
          name: report-main.json
          overwrite: true
