name: Jest Tests

on:
  push:
    branches:
      - main

jobs:
  test-coverage:
    name: Test and Coverage
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: npm ci
      - run: npm run test:ci
      - name: Download
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: comment.yml
          name: report-main.json
          path: artifact
          branch: main
          if_no_artifact_found: warn
      - name: Test Download
        run: cd artigact && ls -l
      - name: Test
        run: |
          node index.js "${{ github.token }}"
        working-directory: "scripts"
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}   