name: Jest Tests

on: 
  pull_request:
    branches:
      - main

jobs:
  test-coverage:
    name: Test and Coverage
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Test
        run: |
          node script.js argumentValue
        working-directory: "scripts"
      
