name: Jest Tests

on: 
  pull_request:
    branches:
      - main

jobs:
  test-coverage:
    name: Test and Coverage
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - run: npm ci
      - name: TestCoverage
        id: testCoverage
        uses: anuraag016/Jest-Coverage-Diff@master
        with:
          fullCoverageDiff: false
          runCommand: npm run test:ci
          delta: 0.5
      # - uses: ArtiomTr/jest-coverage-report-action@v2
      #   with:
      #     # working-directory: "tarpon"
      #     coverage-file: report.json 
      #     base-coverage-file: main-report.json
      #     # test-script: npm run test:ci
      #     annotations: coverage
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}     
