name: Jest Tests

on: 
  pull_request:
    branches:
      - main

jobs:
  test-coverage:
    permissions: write-all
    name: Test and Coverage
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - run: npm ci
      - run: npm run test:ci
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: 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
          # working-directory: "tarpon"
          coverage-file: report.json
          test-script: npm run test:ci
          # base-coverage-file: report.json
