name: Jest Tests

on: 
  pull_request:
    branches:
      - main

jobs:
  test-coverage:
    name: Test and Coverage
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: npm ci
      - run: npm run test:ci
      - name: Download
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: comment.yml
          name: report-main.json
          path: artifact
          branch: main
      - name: Test
        run: |
          node index.js "${{ github.token }}"
        working-directory: "scripts"
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}   