name: Jest Tests

on: 
  pull_request:
    branches:
      - main

jobs:
  test-coverage:
    name: Test and Coverage
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: npm ci
      - run: npm run test:ci
      - uses: actions/download-artifact@v4
        with:
          name: report-main.json
          path: report-main.json 
      - name: Test
        run: |
          node index.js "${{ github.token }}"
        working-directory: "scripts"
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}   