name: Jest Tests

on: 
  pull_request:
    branches:
      - main

jobs:
  test-coverage:
    name: Test and Coverage
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: npm ci
      - run: npm run test:ci
      - name: Test
        run: |
          node index.js "${{ github.token }}"
        working-directory: "scripts"
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}   
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: abcd.txt
          path: output/test/abc.txt
