name: Jest Tests

on: 
  pull_request:
    branches:
      - main

jobs:
  test-coverage:
    name: Test and Coverage
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Debug
        run: echo "Token is ${{ secrets.TOKEN }}"
      
      - run: npm ci
      - run: npm run test:ci
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.TOKEN }}
          # working-directory: "tarpon"
          coverage-file: report.json
          test-script: npm run test:ci
          # base-coverage-file: report.json
